apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  telemetry.yaml: |+
    apiVersion: 1

    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-operated.sa-telemetry.svc:9090
      jsonData:
         timeInterval: "1s"
      version: 1
      editable: true
    - name: influxdb
      type: influxDB
      access: proxy
      orgId: 1
      url: http://pm-poddomain.persist-metrics.svc.cluster.local:8086
      jsonData:
         timeInterval: "1s"
      version: 1
      editable: true
