{
 "title": "Node Drilldown Modified",
 "description": "Drilldown to individual nodes for local metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "promsource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "exported_instances",
    "label": "Cloud Nodes",
    "query": "label_values(exported_instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(sa_collectd_uptime{exported_instance=\"$exported_instances\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Short Term Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(sa_collectd_load_shortterm{exported_instance=\"$exported_instances\"}[1m])"
    }
   ]
  },
  {
   "title": "Mid Term Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(sa_collectd_load_midterm{exported_instance=\"$exported_instances\"}[1m])"
    }
   ]
  },
  {
   "title": "Long Term Load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg_over_time(sa_collectd_load_longterm{exported_instance=\"$exported_instances\"}[1m])"
    }
   ]
  },
  {
   "title": "Disk space utilized (avg over time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sa_collectd_df_percent_bytes{type=\"used\",exported_instance=\"$exported_instances\"}[1m])",
     "legendFormat": "{{df}}"
    }
   ]
  },
  {
   "title": "Disk Time Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "rate(sa_collectd_disk_disk_io_time_io_time_total{exported_instance=\"$exported_instances\"}[1m])",
     "legendFormat": "disk {{disk}}"
    }
   ]
  },
  {
   "title": "TX Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(sa_collectd_interface_if_packets_tx_total{exported_instance=\"$exported_instances\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "RX Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(sa_collectd_interface_if_packets_rx_total{exported_instance=\"$exported_instances\"}[1m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Memory (avg over time, percentage)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(sa_collectd_memory_percent{memory=\"used\",exported_instance=\"$exported_instances\"}[1m])",
     "legendFormat": "{{memory}}"
    }
   ]
  },
  {
   "title": "CPU Percentage Used (avg over time)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(sum(sa_collectd_cpu_percent{type=~\"system|user\",exported_instance=\"$exported_instances\"})by(cpu, exported_instance))by(exported_instance)",
     "legendFormat": "Total CPU Percentage"
    }
   ]
  }
 ]
}