{
 "title": "OpenStack Dashboard Modified",
 "description": "Openstack dashboard using the Openstack Exporter (https://github.com/Linaro/openstack-exporter)",
 "tags": [
  "openstack",
  "openstack-exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster", "query": "label_values(cluster)" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Service status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "panels": [
    {
     "title": "Nova agents down",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(openstack_nova_agent_state{adminState=\"enabled\"})-sum(openstack_nova_agent_state{adminState=\"enabled\"})"
      }
     ]
    },
    {
     "title": "Nova agent status",
     "type": "table",
     "gridPos": { "h": 8, "w": 19, "x": 3, "y": 1 },
     "targets": [
      {
       "expr": "openstack_nova_agent_state{adminState=\"enabled\"}"
      }
     ]
    },
    {
     "title": "Nova agents up",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(openstack_nova_agent_state{adminState=\"enabled\"})"
      }
     ]
    },
    {
     "title": "Cinder agents down",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "(count(openstack_cinder_agent_state{adminState=\"enabled\"})-sum(openstack_cinder_agent_state{adminState=\"enabled\"}))"
      }
     ]
    },
    {
     "title": "Cinder agent status",
     "type": "table",
     "gridPos": { "h": 8, "w": 19, "x": 3, "y": 9 },
     "targets": [
      { "expr": "openstack_cinder_agent_state" }
     ]
    },
    {
     "title": "Cinder agent up",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(openstack_cinder_agent_state{adminState=\"enabled\"})"
      }
     ]
    },
    {
     "title": "Neutron agents down",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(openstack_neutron_agent_state{adminState=\"up\"})-sum(openstack_neutron_agent_state{adminState=\"up\"})"
      }
     ]
    },
    {
     "title": "Neutron agent status",
     "type": "table",
     "gridPos": { "h": 8, "w": 19, "x": 3, "y": 17 },
     "targets": [
      { "expr": "openstack_neutron_agent_state" }
     ]
    },
    {
     "title": "Neutron agents up",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(openstack_neutron_agent_state{adminState=\"up\"})"
      }
     ]
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Overall memory usage (TiB)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent", "label": "Memory in TiB" }
   ],
   "targets": [
    {
     "expr": "openstack_nova_memory_used_bytes/openstack_nova_memory_available_bytes",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Overall CPU cores usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "cores" }
   ],
   "targets": [
    { "expr": "openstack_nova_vcpus_used", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Local Storage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "openstack_nova_local_storage_used_bytes/openstack_nova_local_storage_available_bytes",
     "legendFormat": "local storage used"
    }
   ]
  },
  {
   "title": "Neutron Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "openstack_neutron_floating_ips", "legendFormat": "floating ips" },
    { "expr": "openstack_neutron_networks", "legendFormat": "networks" },
    {
     "expr": "openstack_neutron_security_groups",
     "legendFormat": "security groups"
    },
    { "expr": "openstack_neutron_subnets", "legendFormat": "subnets" }
   ]
  },
  {
   "title": "Keystone stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "openstack_identity_projects", "legendFormat": "projects" },
    { "expr": "openstack_identity_users", "legendFormat": "users" },
    { "expr": "openstack_identity_groups", "legendFormat": "groups" }
   ]
  },
  {
   "title": "Virtual Machines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "openstack_nova_running_vms", "legendFormat": "{{hostname}}-running" },
    { "expr": "openstack_nova_total_vms", "legendFormat": "total" }
   ]
  },
  {
   "title": "Cinder volumes/snapshots",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "openstack_cinder_volumes", "legendFormat": "volumes" },
    { "expr": "openstack_cinder_snapshots", "legendFormat": "snapshots" }
   ]
  },
  {
   "title": "Glance Images",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "openstack_glance_images", "legendFormat": "images" }
   ]
  }
 ]
}