{
 "title": "Cloud Health Modified",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU Highest Activity",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(sa_collectd_cpu_percent[5m])"
    }
   ]
  },
  {
   "title": "Memory Highest Activity",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(sa_collectd_memory_percent[1h])"
    }
   ]
  },
  {
   "title": "Current Top 3 CPU Utilizers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(max by(exported_instance)(topk(3,avg(sum(sa_collectd_cpu_percent{type=~\"system|user\"}) by (exported_instance, cpu)) by (exported_instance))), \"exported_instance_x\", \"$1\", \"exported_instance\", \"mycloud-(.*).cdlj2c.com\")",
     "legendFormat": "{{exported_instance_x}}"
    }
   ]
  },
  {
   "title": "Current Top 3 Memory Utilizers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(max by(memory,exported_instance)(topk(3,max_over_time(sa_collectd_memory_percent{memory=\"used\"}[5m]))), \"exported_instance_x\", \"$1\", \"exported_instance\", \"mycloud-(.*).cdlj2c.com\")",
     "legendFormat": "{{exported_instance_x}}"
    }
   ]
  },
  {
   "title": "Current Lowest 3 Disk Capacity",
   "type": "graph",
   "description": "The three disks on cloud machines with the lowest free percentage",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(bottomk(3, sa_collectd_df_percent_bytes{df=~\"[vs]da.*|mapper.*\",type=\"free\"}), \"exported_instance_x\", \"$1\", \"exported_instance\", \"mycloud-(.*).cdlj2c.com\")",
     "legendFormat": "{{exported_instance_x}}.{{df}}"
    }
   ]
  },
  {
   "title": "Currently Firing Alerts",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  }
 ]
}