{
 "title": "IPMI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "promsource", "label": "DataSource", "query": "prometheus" },
   { "name": "ipmi_instance", "label": "Instance", "query": "label_values(ipmi_instance)" }
  ]
 },
 "panels": [
  {
   "title": "ipmi_sensor_state",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ipmi_sensor_state>0" }
   ]
  },
  {
   "title": "ipmi_temperature_celsius",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "ipmi_temperature_celsius" }
   ]
  },
  {
   "title": "ipmi_power_watts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ipmi_power_watts{ipmi_instance=~\"$ipmi_instance\"}",
     "legendFormat": "{{ipmi_instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "ipmi_voltage_volts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ipmi_voltage_volts{ipmi_instance=~\"$ipmi_instance\"}",
     "legendFormat": "{{ipmi_instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "ipmi_temperature_celsius",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{ipmi_instance=~\"$ipmi_instance\"}",
     "legendFormat": "{{ipmi_instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "ipmi_fan_speed_rpm",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ipmi_fan_speed_rpm{ipmi_instance=~\"$ipmi_instance\"}",
     "legendFormat": "{{ipmi_instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "ipmi_scrape_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ipmi_scrape_duration_seconds", "legendFormat": "{{ipmi_instance}}" }
   ]
  }
 ]
}