apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: prometheus-sa-telemetry
  name: white
  namespace: sa-telemetry
spec:
  # version: v2.11.104
  alerting:
    alert_relabel_configs:
    - regex: (.+)\d+
      source_labels: dc
      target_label: dc
    alertmanagers:
    - name: alertmanager
      namespace: sa-telemetry
      port: web
  # nodeSelector:
  #   application: sa-telemetry
  #   node: white
  podAntiAffinity: hard
  podMetadata:
    labels:
      sa-app: prometheus-white
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: prometheus-sa-telemetry
      role: prometheus-rulefiles
  secrets:
  - alertmanager-token
  securityContext:
    nonroot: true
  serviceAccountName: prometheus-sa
  serviceMonitorSelector:
    matchLabels:
      smartgateway: white
  additionalScrapeConfigs:
    name: prometheus-white-additionalscrapeconfigs
    key: prometheus-additionalScrapeConfigs.yaml
  additionalAlertManagerConfigs:
    name: prometheus-white-additionalalertmanagerconfigs
    key: prometheus-additionalAlertManagerConfigs.yaml
  # storage:
  #   class: ""
  #   resources: {}
  #   selector: {}
  #   volumeClaimTemplate:
  #     spec:
  #       resources:
  #         requests:
  #           storage: 20G
  #       storageClassName: manual
  version: v2.3.2
